/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app_v1.GUI;

import app_v1.Flight.FlightInfo;
import app_v1.Flight.FlightSearch;
import app_v1.User.UserInfo;
import app_v1.User.UserOptions;
import static app_v1.User.UserOptions.user_type.ARMED_FORCES;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
//import javax.xml.ws.soap.MTOM;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import app_v1.Flight.IFlighSearch;
import java.util.Date;

/**
 *
 * <h1>Main Flight Search Page</h1>
* This page allows user to search for new flights
* according to his/her preference and 
* also allows to add the selected flights as favourite
* so that the user can check it later
 * @author Rohan
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public UserInfo m_userInfo;

    IFlighSearch m_searchRoutes;
    static Favourite m_viewFav = new Favourite();

    public Main() {
        m_viewFav = new Favourite();
        m_searchRoutes = new FlightSearch();
        FlightSearch.CreateTable();
        initComponents();
        AutoCompleteDecorator.decorate(jComboBox1);
        AutoCompleteDecorator.decorate(jComboBox2);
        Date date = new Date();
        /**
         * setting minimum selectable date of calendar to current date
         */
        jDateChooser2.getJCalendar().setMinSelectableDate(date);  
        jDateChooser3.getJCalendar().setMinSelectableDate(date);
        jButton2.setEnabled(false);
        if (jRadioButton1.isSelected()) {
            jPanel1.setVisible(false);
            jDateChooser3.setCalendar(null);
            jDateChooser3.setEnabled(false);
            jLabel8.setVisible(false);
        } else if (jRadioButton2.isSelected()) {
            jPanel1.setVisible(true);
            jDateChooser3.setEnabled(true);
            jLabel8.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jDateChooser3 = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Flight API");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Pune", "Mumbai", "Montreal", "Frankfurt", "Delhi" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Pune", "Mumbai", "Montreal", "Frankfurt", "Delhi" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jButton1.setText("Search Flights");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jDateChooser2.setDateFormatString("yyyy-MM-dd");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Carrier", "Origin", "Destination", "Price", "ID", "Add To Fav"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jDateChooser3.setDateFormatString("yyyy-MM-dd");

        jLabel2.setText("Origin");

        jLabel3.setText("Destination");

        jLabel4.setText("Departure Date");

        jLabel5.setText("Return Date");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("One Way");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Return");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jLabel6.setText("Currency");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "INR", "CAD", "USD", "EUR" }));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Carrier", "Origin", "Destination", "Price", "ID", "Add To Fav"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        jLabel7.setText("Outbound");

        jLabel8.setText("Return");

        jButton2.setText("Add Selected Flights To Favourite");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel9.setText("User Name : ");

        jLabel10.setText("jLabel10");

        buttonGroup2.add(jRadioButton3);
        jRadioButton3.setText("Armed Forces");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jLabel11.setText("Fare Type:");

        jLabel12.setText("Travel Type:");

        buttonGroup2.add(jRadioButton4);
        jRadioButton4.setText("Student");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButton5);
        jRadioButton5.setText("Senior Citizen");

        buttonGroup2.add(jRadioButton6);
        jRadioButton6.setSelected(true);
        jRadioButton6.setText("Regular");

        jButton3.setText("My Favourites");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Sign Out");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(68, 68, 68))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel11))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRadioButton1)
                                            .addComponent(jRadioButton6))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jRadioButton3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jRadioButton4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jRadioButton5))
                                            .addComponent(jRadioButton2)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel5)
                                            .addComponent(jDateChooser3, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton1))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(jLabel8))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addGap(436, 436, 436)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(80, 80, 80))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jButton3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton3)
                    .addComponent(jLabel11)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton5)
                    .addComponent(jRadioButton6))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 299, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(101, 101, 101))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:


        if (jComboBox1.getSelectedItem().toString().trim().equals("") || jComboBox2.getSelectedItem().toString().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Origin Or Destination Cannot Be Blank", "Flight API Error", JOptionPane.ERROR_MESSAGE);
        } else if (jComboBox1.getSelectedItem().toString().equals(jComboBox2.getSelectedItem().toString())) {
            JOptionPane.showMessageDialog(this, "Origin and Destination Cannot Be The Same", "Flight API Error", JOptionPane.ERROR_MESSAGE);
        } else if (jDateChooser2.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Departure Date Cannot Be Blank", "Flight API Error", JOptionPane.ERROR_MESSAGE);
        } else if (jRadioButton2.isSelected() && jDateChooser3.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Return Date Cannot Be Blank", "Flight API Error", JOptionPane.ERROR_MESSAGE);
        } else {
            DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            String strDateOut = df.format(jDateChooser2.getDate());
            String strDateIn = "";
            if (jRadioButton2.isSelected()) {
                strDateIn = df.format(jDateChooser3.getDate());
            }

            String originPlace = jComboBox1.getSelectedItem().toString(), destinationPlace = jComboBox2.getSelectedItem().toString();

            if (originPlace.equals("Pune")) {
                originPlace = "PNQ";
            } else if (originPlace.equals("Mumbai")) {
                originPlace = "BOM";
            } else if (originPlace.equals("Montreal")) {
                originPlace = "YUL";
            } else if (originPlace.equals("Frankfurt")) {
                originPlace = "FRA";
            }
            else if (originPlace.equals("Delhi")) {
                originPlace = "DEL";
            }

            if (destinationPlace.equals("Pune")) {
                destinationPlace = "PNQ";
            } else if (destinationPlace.equals("Mumbai")) {
                destinationPlace = "BOM";
            } else if (destinationPlace.equals("Montreal")) {
                destinationPlace = "YUL";
            } else if (destinationPlace.equals("Frankfurt")) {
                destinationPlace = "FRA";
            }
            else if (originPlace.equals("Delhi")) {
                originPlace = "DEL";
            }

            UserOptions userOptions = new UserOptions("IN",
                    jComboBox3.getSelectedItem().toString(),
                    strDateOut,
                    strDateIn,
                    m_userInfo.m_id,
                    originPlace,
                    destinationPlace);

            try {
/**
                * getting the list of flights as required by user
                */
                ArrayList<FlightInfo> flights = m_searchRoutes.GetFlights(userOptions);  
                
                

                DefaultTableModel tblModel = (DefaultTableModel) jTable1.getModel();
                int rowstoremove = tblModel.getRowCount();

                for (int a = rowstoremove - 1; a >= 0; a--) {   //clearing the table before every new search
                    tblModel.removeRow(a);
                }

                DefaultTableModel tblModel2 = (DefaultTableModel) jTable2.getModel();
                int rowstoremove2 = tblModel2.getRowCount();
                for (int a = rowstoremove2 - 1; a >= 0; a--) {
                    tblModel2.removeRow(a);
                }
                
                UserOptions.user_type userType = UserOptions.user_type.REGULAR_FARE;
                /**
                        *Checking the fare type selected by the user
                
                */
                if(!jRadioButton6.isSelected())  
                {
                    if (jRadioButton3.isSelected()) 
                        userType = ARMED_FORCES;
                    else if (jRadioButton4.isSelected())
                        userType = ARMED_FORCES;
                    else if (jRadioButton5.isSelected())
                         userType = ARMED_FORCES;
                    /**
                     * getting the prices according to the fare type selected
                     */
                    flights = m_searchRoutes.GetDiscountedPrices(userType); 
                }
                /**
                     * Displaying the records to the user
                     */
                for (int i = 0; i < flights.size(); i++) {  
                    FlightInfo f = flights.get(i);
                    
                    String tabledata[] = {String.valueOf(f.getOutCarrier()), f.getOriginAirport(), f.getDestinationAirport(), Double.toString(f.getPrice()), Integer.toString(f.getFlightID())};

                    tblModel.addRow(tabledata);

                    String tabledata2[] = {String.valueOf(f.getInCarrier()), f.getDestinationAirport(), f.getOriginAirport(), Double.toString(f.getPrice()), Integer.toString(f.getFlightID())};

                    tblModel2.addRow(tabledata2);

                }

                int rowcount = tblModel.getRowCount();
/**
                     * checking if atleast one record is present , else disabling the add to favourites button
                     */
                if (rowcount > 0) {  
                    jButton2.setEnabled(true);
                } else {
                    jButton2.setEnabled(false);
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    }
    /**
                     * clearing the previously displayed records each time the user changes travel type and setting the visibility of the tables accordingly
                     */
    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed

        if (jRadioButton1.isSelected()) {
             DefaultTableModel tblModel = (DefaultTableModel) jTable1.getModel();
                int rowstoremove = tblModel.getRowCount();

                for (int a = rowstoremove - 1; a >= 0; a--) {
                    tblModel.removeRow(a);
                }
                

                DefaultTableModel tblModel2 = (DefaultTableModel) jTable2.getModel();
                int rowstoremove2 = tblModel2.getRowCount();
                for (int a = rowstoremove2 - 1; a >= 0; a--) {
                    tblModel2.removeRow(a);
                }
            jPanel1.setVisible(false);
            jDateChooser3.setCalendar(null);
            jDateChooser3.setEnabled(false);
            jLabel8.setVisible(false);
        } else if (jRadioButton2.isSelected()) {
            jPanel1.setVisible(true);
            jDateChooser3.setEnabled(true);
            jLabel8.setVisible(true);
        }
    }//GEN-LAST:event_jRadioButton1ActionPerformed
/**
                     * clearing the previously displayed records each time the user changes travel type and setting the visibility of the tables accordingly
                     */
    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed

        if (jRadioButton1.isSelected()) {
            jPanel1.setVisible(false);
            jDateChooser3.setEnabled(false);
            jLabel8.setVisible(false);
        } else if (jRadioButton2.isSelected()) {
             DefaultTableModel tblModel = (DefaultTableModel) jTable1.getModel();
                int rowstoremove = tblModel.getRowCount();

                for (int a = rowstoremove - 1; a >= 0; a--) {
                    tblModel.removeRow(a);
                }
                

                DefaultTableModel tblModel2 = (DefaultTableModel) jTable2.getModel();
                int rowstoremove2 = tblModel2.getRowCount();
                for (int a = rowstoremove2 - 1; a >= 0; a--) {
                    tblModel2.removeRow(a);
                }
            jPanel1.setVisible(true);
            jDateChooser3.setEnabled(true);
            jLabel8.setVisible(true);
        }
    }//GEN-LAST:event_jRadioButton2ActionPerformed
        /**
                     * adding the user selected flights to his/her favourites tab
                     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

       DefaultTableModel tblModel = (DefaultTableModel) jTable1.getModel();
        int rowcount = tblModel.getRowCount();

        for(int i = 0;i<rowcount;i++){
       
           if(tblModel.getValueAt(i, 5) != null && tblModel.getValueAt(i, 5).toString().trim().equals("true")){
               
               m_searchRoutes.SaveFlights(m_userInfo.m_id, Integer.parseInt(tblModel.getValueAt(i, 4).toString()));

           }
        }
        
        if(jRadioButton2.isSelected()){
            DefaultTableModel tblModel2 = (DefaultTableModel) jTable2.getModel();
        int rowcount2 = tblModel2.getRowCount();
        for(int i = 0;i<rowcount2;i++){
       
           if(tblModel2.getValueAt(i, 5) != null && tblModel2.getValueAt(i, 5).toString().trim().equals("true")){
               
               m_searchRoutes.SaveFlights(m_userInfo.m_id, Integer.parseInt(tblModel2.getValueAt(i, 4).toString()));

           }
        }
        }
        
        JOptionPane.showMessageDialog(this, "Selected Flights Have Been Added To Your Favourites");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed
/**
 * opening the Favourites Tab
 */
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        

        m_viewFav.m_userId = m_userInfo.m_id;
        m_viewFav.jLabel3.setText(jLabel10.getText());
        m_viewFav.DisplayFavoriteFlights();
        m_viewFav.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed
         /**
                     * Button to signout the user
                     */
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

        UserLogin viewsignin = new UserLogin();
        viewsignin.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }

        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
